# Use a lightweight web server as the base image
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
# Copy the static files to the web server root directory

RUN npm install

COPY . . 

# Expose the default HTTP port
EXPOSE 80

# Start the web server
CMD ["nginx", "-g", "daemon off;"]
