# Use a base Node.js image
FROM node:14

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the backend source code
COPY . .


# Expose the default port used by the backend
EXPOSE 3000

# Start the backend server
CMD ["node", "index.js"]
